Bootstrap: docker
From: centos:8

%setup

%files

%help

   A container with R, Bioconductor and MethylKit installed on top of basic bioinformatics tools. For complete list see documentation of shub://thakk/bioinformatics

%labels
   Author francesco.tabaro@tuni.fi
   Version 0.1

%post
  
  NOW=`date`
  dnf -y makecache

  echo "export NOW=\"${NOW}\"" >> $SINGULARITY_ENVIRONMENT
  set -e

  dnf -y group install "Development Tools"
  dnf -y install --allowerasing hostname which dnf-utils \
    python3-pip git zlib zlib-devel bzip2 bzip2-devel \
    xz xz-devel libcurl libcurl-devel ncurses ncurses-devel \
    unzip wget gnuplot rsync java-1.8.0-openjdk java-1.8.0-openjdk-devel \
    openssl-devel libffi-devel python36-devel \
    bzip2 cairo fontconfig freetype fribidi glib2 \
    libX11 libXext libXt libcurl libicu libjpeg libpng libtiff libtirpc libxcrypt \
    ncurses pango pcre readline tcl tk xz zlib bzip2-devel cairo-devel \
    fontconfig-devel freetype-devel fribidi-devel glib2-devel libX11-devel \
    libXext-devel libXt-devel libcurl-devel libicu-devel libjpeg-devel libpng-devel \
    libtiff-devel libtirpc-devel libxcrypt-devel ncurses-devel pango-devel \
    pcre-devel readline-devel tcl-devel tk-devel xz-devel zlib-devel \
    java-1.8.0-openjdk java-1.8.0-openjdk-devel openblas lapack \
    gcc-gfortran boost boost-devel texlive libxml2-devel

  ln -s /usr/bin/python3 /usr/bin/python
  ln -s /usr/bin/pip3 /usr/bin/pip

  pip install numpy pandas matplotlib scikit-learn scipy opencv-contrib-python

  # Intel Threading Building Blocks 2019 U8
  echo "/usr/local/lib" >> /etc/ld.so.conf.d/usr_local_lib.conf
  rm -rf tbb
  git clone https://github.com/intel/tbb
  cd tbb
  make -j 8
  find . -name '*so' | grep release | xargs -I{} cp {} /usr/local/lib/  # Copy release libs to sys dir
  find . -name '*so.2' | grep release | xargs -I{} cp {} /usr/local/lib/
  cp -R include/* /usr/local/include/
  cd ..
  ldconfig
  mkdir -p /usr/local/lib64/python3.6/site-packages

# ################### Samtools #################################

%apprun samtools
   exec samtools

%appinstall samtools
   rm -rf htslib
   git clone https://github.com/samtools/htslib
   cd htslib
   autoheader
   autoconf
   ./configure
   make -j 8
   make install
   cd ..
   rm -rf samtools
   git clone https://github.com/samtools/samtools
   cd samtools
   autoheader
   autoconf -Wno-syntax
   ./configure
   make -j 8
   make install
   cd ..

%apphelp samtools
   Samtools 1.9. https://github.com/samtools/samtools

# ######################## Bowtie2 ################################

%apprun bowtie2
   exec bowtie2

%appinstall bowtie2
   wget -O bowtie.zip https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.5.1/bowtie2-2.3.5.1-source.zip/download
   unzip -o bowtie.zip
   cd bowtie2-2.3.5.1
   make -j 8
   cp bowtie2* /usr/local/bin/
   cd ..


%apphelp bowtie2
   Bowtie 2 v. 2.3.5.1 . http://bowtie-bio.sourceforge.net/bowtie2/index.shtml

# ######################## Cutadapt ################################

%apprun cutadapt
   exec cutadapt

%appinstall cutadapt
   pip install cutadapt

%apphelp cutadapt
   Cutadapt 2.4.. https://cutadapt.readthedocs.io/en/stable/guide.html

# ############################ TrimGalore ########################

%apprun trim_galore
   exec trim_galore

%appinstall trim_galore
   curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.6.5.tar.gz -o trim_galore.tar.gz
    tar xzf trim_galore.tar.gz
    cp TrimGalore-0.6.5/trim_galore /usr/local/bin
    rm -r TrimGalore-0.6.5


%apphelp trim_galore
    TrimGalore (0.6.5) . https://github.com/FelixKrueger/TrimGalore

# ############################ Bismark ########################

%apprun bismark
   exec bismark

%appinstall bismark
    curl -fsSL https://github.com/FelixKrueger/Bismark/archive/0.22.3.tar.gz -o Bismark_0.22.3.tar.gz
    tar xzf Bismark_0.22.3.tar.gz -C /opt/

%apphelp bismark
    Bismark (0.22.3) . https://github.com/FelixKrueger/Bismark

# ############################ R + Bioconductor + methylKit ########################

%apprun R
   exec R

%apphelp R
    R (4.0.2) . https://www.r-project.org/

%appinstall R
 
  wget https://cran.r-project.org/src/base/R-4/R-4.0.2.tar.gz
  tar xf R-4.0.2.tar.gz
  cd R-4.0.2
  ./configure && make -j4 && make install
  cd ..
  rm -r R-4.0.2

  R -e "install.packages('BiocManager', repos = 'https://cloud.r-project.org')"
  R -e "BiocManager::install(version = '3.11')"
  R -e "BiocManager::install('methylKit')"



